print('Hallo gebruiker!')
Uren = input('Hoeveel uren heb je gewerkt?')
Uurloon = input('Wat is je uurloon?')
Salaris = int(Uren)*float(Uurloon)
line = 'gebruiker u salaris wordt' + str(Salaris)
print(line)